function [rain_attenuation]=rain_attenuation(lat,lon,f,E,p,hs,to)
    % lat = Latitude (°)
    % lon = Logitude (°)
    % hs  = Earth station altitude (km)
    % E   = Link elevation angle (rad)
    % f   = Link frequency (GHz)
    % to  = Tilt polarization angle (°)
    % D   = Earth station antenna diameter (m)
    % eta = Earth station antenna efficiency
    % p   = Percentage of the time (%)
    
    [status, command_output] = system(['rain_attenuation.exe'...
                                ' ' num2str(lat) ...
                                ' ' num2str(lon)...
                                ' ' num2str(f)...
                                ' ' num2str(E)...
                                ' ' num2str(p)...
                                ' ' num2str(hs)...
                                ' ' num2str(to)]);
        rain_attenuation = str2double(command_output);