function [scintillation] = scintillation(lat, lon, f, E, p,hs,eta,D)
    % lat = Latitude (°)
    % lon = Logitude (°)
    % hs  = Earth station altitude (km)
    % E   = Link elevation angle (rad)
    % f   = Link frequency (GHz)
    % to  = Tilt polarization angle (°)
    % D   = Earth station antenna diameter (m)
    % eta = Earth station antenna efficiency
    % p   = Percentage of the time (%)
    
    [status, command_output] = system(['scintillation.exe'...
                                ' ' num2str(lat) ...
                                ' ' num2str(lon)...
                                ' ' num2str(f)...
                                ' ' num2str(E)...
                                ' ' num2str(p)...
                                ' ' num2str(hs)...
                                ' ' num2str(eta)...
                                ' ' num2str(D)]);
        scintillation = str2double(command_output);
